### ISSUE TITLE
Installed node will not show up in Node pallet when using Raspberry Chromium web browser

### ISSUE THREAD

**Issue by SiemensBleuler** [mindsphere/node-red-contrib-mindconnect#103] opened 2020-09-16 11:52 UTC
**Describe the bug**
After updating from 3.8.1 to 3.9.0 the installed does not show up in the pallet anymore. Accessing the same node-RED instance from another client running regular Chrome shows the node just fine. 

**To Reproduce**

- Open Node-RED in Raspberry Chromium 
- Try to use version 3.9.0

**Screenshots**
![2020-09-16-134608_1024x768_scrot](https://user-images.githubusercontent.com/57528264/93333618-dfc51380-f823-11ea-99f5-b1070e0ee69b.png)

**Desktop (please complete the following information):**
RaspberryOS 3B+

**Comment by sn0wcat** [comment] 2020-09-16 11:55
@SiemensBleuler could you take a look in the developer console (if there is one) if there are some chromium errors showing?)

**Comment by SiemensBleuler** [comment] 2020-09-16 12:02
![image(1)](https://user-images.githubusercontent.com/57528264/93334476-4c8cdd80-f825-11ea-9eac-1061ba439c8c.png)

**Comment by sn0wcat** [comment] 2020-09-16 13:19
ok, i can reproduce it @SiemensBleuler  I will take a look what is different between the chromium on raspberry and chrome loading of the node. (chromium on x86 is working btw.)

![image](https://user-images.githubusercontent.com/1426617/93342717-f3767700-f82f-11ea-99c3-b51cc8f8d78c.png)

**Comment by sn0wcat** [comment] 2020-09-16 16:17
@SiemensBleuler could you check the version of the chromium which you are using on your raspberry, and then update chromium and restart and check if that fixed the problem? I had to reboot my raspberry (it had pending updates) and now everything works. This seems to be connected to the version of chromium you have on your raspberry:

![image](https://user-images.githubusercontent.com/1426617/93364352-bd91bc80-f848-11ea-8e19-2d80b1165bbb.png)

![image](https://user-images.githubusercontent.com/1426617/93364440-d7330400-f848-11ea-9cbe-0de93f8f8678.png)

**Comment by sn0wcat** [comment] 2020-09-16 19:54
published the version 3.9.1 to close this issue

**Comment by sn0wcat** [comment] 2020-09-16 19:55
@SiemensBleuler version 3.9.1 should work now, also without upgrading chromium

**Closed by sn0wcat** 2020-09-16 19:55 UTC
Labels: bug

**Comment by sn0wcat** [comment] 2020-09-17 07:51
@SiemensBleuler Please tell me once you have upgraded if the problems are gone :)

**Comment by SiemensBleuler** [comment] 2020-09-19 11:28
Okay, thanks. I will check if it works once I am back in the office next week.

Am 17.09.2020 um 09:51 schrieb sn0wcat <notifications@github.com>:

﻿

@SiemensBleuler<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSiemensBleuler&data=02%7C01%7Creto.bleuler%40siemens.com%7C06e455d0d6e940073a8608d85ade7bde%7C38ae3bcd95794fd4addab42e1495d55a%7C1%7C0%7C637359258890641209&sdata=fzlX0gbKcsc%2Fnyt3OzBkDTltlfaEgRRylHbTZcbRHvI%3D&reserved=0> Please tell me once you have upgraded if the problems are gone :)
